### ISSUE TITLE
프로젝트 개발 준비 작업

### ISSUE THREAD

**Issue by hyunolike** [hyunolike/weather-web.landing#1]
### 📄 Describe

프로젝트 개발 전 기본 폴더 구조와 필요한 라이브러리 준비를 하려고 합니다.

### ✅ Tasks

- [x] 폴더 구조 잡기
- [x] 필요한 라이브러리 확인 및 준비
- [x] 컴포넌트 구조 대략 잡기

### 🙋🏻 More

완벽하게 하려하지 말고 필요하다 싶은 것만 준비!
